// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
}
export {}
